### ISSUE TITLE
Need a working example of bulk insertion from database

### ISSUE THREAD

**Issue by hume12** [manticoresoftware/go-sdk#17]
I have difficulty creating a function to populate a table and insert a range of rows in it upon a http get requst. 

Here is what I came up with:

```
func FillManticore(w http.ResponseWriter, r *http.Request) {
	cl := manticore.NewClient()
	cl.SetServer("127.0.0.1", 9312)
	cl.Open()
        //first drop table to start from scratch
	res, err := cl.Sphinxql(`DROP TABLE ads_search`)
        //create a fresh table 
	q := "CREATE TABLE ads_search (title text)"
	res, err = cl.Sphinxql(q)
        //query MySQL 
        //iterate over rows (a slice of type ad structs) and insert into manticore
	for i, ad := range ads {
		q := "INSERT INTO ads_search (title) VALUES (\"" + ad.Title + "\")"
		res, err := cl.Sphinxql(q)
		fmt.Println("iteration:"+strconv.Itoa(i), res, err)
	}
       // respond that the table is populated}
      }
```

This should be trivial but I get loads of  erros like:

```
[ERROR 1064 (42000): sphinxql: syntax error, unexpected $undefined near '"Used Car")'] <nil>
[ERROR 1064 (42000): sphinxql: syntax error, unexpected $undefined near '"NY Hat")'] <nil
```>
Unfortunately I could not find any such scenario in the docs. So appreciate your help.

**Comment by sanikolaev** [comment]
Hi. Could you update the code please as now it doesn't seem to be related with the output as it's missing:
* "create query is"
* "error droping table"

**Comment by hume12** [comment]
Sorry those were just println outputs. Just removed them.

**Comment by sanikolaev** [comment]
When I run:

```go
package main

import "github.com/manticoresoftware/go-sdk/manticore"
import "fmt"

func main() {

        cl := manticore.NewClient()
        cl.SetServer("127.0.0.1", 9312)
        cl.Open()
        //first drop table to start from scratch
        res, err := cl.Sphinxql(`DROP TABLE ads_search`)
        //create a fresh table
        q := "CREATE TABLE ads_search (title text)"
        res, err = cl.Sphinxql(q)
        //query MySQL
        //iterate over rows (a slice of type ad structs) and insert into manticore
        for i, ad := range ads {
                q := "INSERT INTO ads_search (title) VALUES (\"" + ad.Title + "\")"
                res, err := cl.Sphinxql(q)
                fmt.Println("iteration:"+strconv.Itoa(i), res, err)
        }
       // respond that the table is populated}

}
```

I get 

```
➜  ~ go run manticore.go
# command-line-arguments
./manticore.go:18:21: undefined: ads
./manticore.go:21:28: undefined: strconv
```

Can you please provide an example which fully reproduces the problem?

**Comment by klirichek** [comment]
Good day, @hume12 

1-st, strings in sql syntax are '-enclosed, not "-enclosed. So, 'insert .. values ( ... "something")' will definitely fail.
2-nd, for such usage that might be more convenient to use direct sql connection via mysql driver, to a port listening on mysql proto. In that case API 'sphinxql' command is just a wrapper; it just provides very base transport of your sql line into manticore, i.e. it works just instead of true mysql connection; when payload delivered, the rest just processed by internal mysql engine. You may just directly connect by mysql proto instead, and for bulk inserts using 'compressed' proto might also have sense as it decreases network footprint. The only benefit of using 'api' in this case might be NOT using mysql proto (and bring code for mysql connector into your app), however don't think that is a big deal in case of go lang.

You can always connect to manticore daemon using mysql console client (no name, no password, just port is necessary) - as 'mysql -h0 -P9306' in case daemon listening port 9306 for mysql connections. And when necessary command created, you can then put it into your application and send whatever method you want - either via 'sphinxql' api command with binary api proto, either as true mysql command using mysql proto.

**Comment by dimuska139** [comment]
@hume12 you are using double quotes instead of single quotes. Try this `q := "INSERT INTO idx_ads (title) VALUES ('" + ad.Title + "')"`:
```
iteration:0 [Query OK, 1 rows affected] <nil>
iteration:1 [Query OK, 1 rows affected] <nil>
iteration:2 [Query OK, 1 rows affected] <nil>
```
@sanikolaev I think this issue can be closed

**Comment by sanikolaev** [comment]
Right. Thanks for your comment @dimuska139 . I'm closing this issue.
